- hosts: leafspine
  name: startup
  become: yes
  gather_facts: no
  ignore_errors: yes
  tasks:
    - name: clean startup.yaml and set hostname
      copy:
        src: /home/cumulus/ON-18/cleanup/{{ inventory_hostname }}.yaml
        dest: /etc/nvue.d/startup.yaml
    # aktivieren
    - name: activate changes for all cumulus nodes
      shell:  nv config apply startup -y
      
      
- hosts: host
  name: netplan
  become: yes
  gather_facts: no
  tasks:
    - name: cloud file entfernen
      ansible.builtin.file:
        path: /etc/netplan/50-cloud-init.yaml
        state: absent
    - name: cloud file entfernen
      ansible.builtin.file:
        path: /etc/netplan/config.yaml
        state: absent
    - name: copy netplan yaml
      copy:
        src: /home/cumulus/ON-18/cleanup/{{ inventory_hostname }}.yaml
        dest: /etc/netplan/config.yaml
    - name: apply netplan yaml
      shell: netplan apply
      # danke netplan
    - name: Unconditionally reboot the machine with all defaults
      ansible.builtin.reboot:
