-
  hosts: host3
  become: true
  user: ubuntu
  gather_facts: false

  tasks:
    - name: add cumulus user
      ansible.builtin.user: 
        name: cumulus
        group: admin
        shell: /bin/bash
        comment: "admin user"
        password: "$6$alq$WRoBPYvpxl0kxnfgcCB6SZ1MxRmBV8/aHhwGAOn17fp8pszaAsVzxy7qPUBHX71ovin1epXCbleKgiUcqlrzT1"  
