#!/bin/bash

# ALQ, 汉堡 二零二三 年

sudo ansible-playbook /home/ubuntu/ON-18/.main.yaml

USER="cumulus"
USERPASS="Academy123"
CUMULUS_HOME="/home/cumulus"
KEYLOCATION="$CUMULUS_HOME/.ssh/authorized_keys"

sudo -i -u cumulus bash << EOF
  echo "USER :$USER"
  echo "DIR  :$PWD"
  cd "$CUMULUS_HOME"
  echo "DIR :$PWD"

  if [ ! -d "$CUMULUS_HOME/ON-18" ]; then
    git clone https://github.com/laquiante/ON-18
    echo "git clone done"
  fi
  if [ -d "$CUMULUS_HOME/ON-18" ]; then
    cd $CUMULUS_HOME/ON-18
    sudo chmod 744 $CUMULUS_HOME/ON-18/prepare
    export PATH="$CUMULUS_HOME/ON-18/:$PATH" 
    echo "calling /home/cumulus/ON-01/prepare"
    sudo bash "$CUMULUS_HOME/ON-01/prepare"
  fi

EOF
