#!/bin/bash
# -*- tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil -*-

# ALQ, Hamburg 2023

PFAD="$HOME/ON-18/starts"
sudo ansible-playbook -i /home/cumulus/ON-18/inventory/files/hosts $PFAD/api_file.yaml

erg=$(curl  -u 'cumulus:CumulusLinux!' --insecure https://192.168.200.2:8765/cue_v1/interface)
echo "$erg"

if [[ $erg == *"Authorization Required"* ]]; then
  echo $WARNUNG
fi

curl -u 'cumulus:CumulusLinux!' --insecure https://192.168.200.2:8765/cue_v1/interface

# Zum Testen

#erg=$(curl  -u 'cumulus:BadPassword' --insecure https://192.168.200.2:8765/cue_v1/interface)

#if [[ $erg == *"Authorization Required"* ]]; then
#  echo $WARNUNG
#fi

exit 0
