---
- hosts: leafspine
  name: startup
  become: yes
  gather_facts: no
  tasks:
    - name: practice-07
      copy:
        src: /home/cumulus/ON-18/labs/troubleshooting-L3/{{ inventory_hostname }}
        dest: /etc/nvue.d/startup.yaml
    # aktivieren
    - name: activate changes for leaf
      shell: nv config apply startup -y

- hosts: host
  name: netplan
  become: yes
  gather_facts: no
  tasks:
    - name: copy netplan yaml
      copy:
        src: /home/cumulus/ON-18/labs/troubleshooting-L3/{{ inventory_hostname }}
        dest: /etc/netplan/config.yaml
    - name: apply netplan
      shell: netplan apply
    - name: verification
      ansible.builtin.shell: /sbin/ip -br a
      register: ipa
    - debug: msg={{ ipa.stdout }}

    # Fehlerbild
    # host1 kann sein default-gateway erreichen aber es treten doppelte Pakete auf
    # host2 kann sein default-gateway nicht erreichen
    # host1 kann nicht host4 erreichen
