---
- hosts: leafspinesuperspine5
  name: startup
  become: yes
  gather_facts: no
  tasks:
    - name: practice-10
      copy:
        src: /home/cumulus/ON-18/labs/practice-10/{{ inventory_hostname }}
        dest: /etc/nvue.d/startup.yaml
    # aktivieren
    - name: activate changes for leaf
      shell: nv config apply startup -y

- hosts: hostall
  name: netplan
  become: yes
  gather_facts: no
  tasks:
    - name: copy netplan yaml
      copy:
        src: /home/cumulus/ON-18/labs/practice-10/{{ inventory_hostname }}
        dest: /etc/netplan/config.yaml
    - name: apply netplan
      shell: netplan apply
    - name: verification
      ansible.builtin.shell: /sbin/ip -br a
      register: ipa
    - debug: msg={{ ipa.stdout }}
